__author__ = 'junyu'
class SqlConstants:
    INSERT_HTML_TAGS = "INSERT INTO HTML_TAG (TAG_NAME,ATTRIBUTE,VALUE,`ORDER`,CRAWLER_ID) VALUES(%s,%s,%s,%s,%s)"

    INSERT_T_CRAWLER = "INSERT INTO T_CRAWLER (NAME,URL,CATEGORY_ID,AUTHOR,NEXT_RUN_TIME,`INTERVAL`, CHARSET) VALUES(%s,%s,%s,%s,NOW(),%s,%s)"

    QUERY_HTML_TAGS_BY_T_CRAWLER_ID = """
SELECT TAG_NAME,ATTRIBUTE,VALUE,`ORDER`
FROM html_tag
WHERE CRAWLER_ID = '%s'
ORDER BY `ORDER` ASC"""

    QUERY_HTML_TAG_BY_ID = """
SELECT TAG_NAME,ATTRIBUTE,VALUE,`ORDER`
FROM html_tag
WHERE ID = '%s'
ORDER BY `ORDER` ASC"""


    QUERY_TCRAWLERS_CATEGORY = """
SELECT ID,NAME,URL,CATEGORY_ID,AUTHOR,NEXT_RUN_TIME,`INTERVAL`, CHARSET, FILTER_WORDS, BLOG_TAG_ID
FROM  T_CRAWLER WHERE CATEGORY_ID = %s ORDER BY NEXT_RUN_TIME ASC LIMIT %s
    """

    QUERY_TCRAWLER_BY_ID = """
SELECT ID,NAME,URL,CATEGORY_ID,AUTHOR,NEXT_RUN_TIME,`INTERVAL`, CHARSET, FILTER_WORDS, BLOG_TAG_ID
FROM  T_CRAWLER WHERE ID = %s
    """

    INSERT_BLOG = "INSERT INTO BLOG(TITLE,AUTHOR,CONTENT,VIEW_NUM,WEIGHT,URL,CATEGORY_ID,CREATE_TIME) VALUES(%s,%s,%s,0,%s,%s,%s,NOW())"

    IS_BLOG_EXIST_BY_TITLE = """SELECT COUNT(1) FROM BLOG WHERE TITLE = '%s'"""

    UPDATE_TIME_T_CRAWLER = """UPDATE T_CRAWLER SET NEXT_RUN_TIME = '%s' WHERE ID = %s"""

    UPDATE_TIME_CATEGORY = """UPDATE CATEGORY SET NEXT_RUN_TIME = '%s' WHERE CATEGORY_ID = %s"""

    UPDATE_PORTAL_SHOW = """
    UPDATE PORTAL_SHOW
SET BLOG_ID = %s, update_time = NOW()
WHERE BLOG_ID =
(
SELECT A.BLOG_ID
FROM
(
SELECT P.BLOG_ID
FROM PORTAL_SHOW AS P
WHERE AREA_ID = 2
ORDER BY P.update_time ASC
LIMIT 1
) A
)
    """

    DELETE_BLOG = "DELETE FROM BLOG WHERE ID = %s"

    QUERY_CATEGORIES_BY_ID = "SELECT CATEGORY_ID, CATEGORY_NAME,NEXT_RUN_TIME,`INTERVAL`,UPDATE_BLOG_NUM FROM CATEGORY WHERE LEVEL = %s"